// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for client documents
 */
interface ClientDocumentData {
  /**
   * name field in *client*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * client document from Prismic
 *
 * - **API ID**: `client`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ClientDocumentData>, "client", Lang>;

type HomeDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for industry documents
 */
interface IndustryDocumentData {
  /**
   * name field in *industry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * industry document from Prismic
 *
 * - **API ID**: `industry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndustryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndustryDocumentData>,
    "industry",
    Lang
  >;

/**
 * Item in *project → Project Services*
 */
export interface ProjectDocumentDataProjectServicesItem {
  /**
   * Service field in *project → Project Services*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_services[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<"service">;
}

type ProjectDocumentDataSlicesSlice =
  | ProjectTwoImagesSlice
  | ProjectVideoVimeoSlice
  | ProjectVideoUrlSlice
  | ProjectImagesSlice
  | ProjectEmbedSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * name field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: project name
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * cover image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * date field in *project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: date
   * - **API ID Path**: project.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * is_featured field in *project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.is_featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_featured: prismic.BooleanField;

  /**
   * description field in *project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: description
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * client field in *project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  client: prismic.ContentRelationshipField<"client">;

  /**
   * Project Services field in *project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_services[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_services: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectServicesItem>
  >;

  /**
   * Industries field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.industries
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  industries: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Content for service documents
 */
interface ServiceDocumentData {
  /**
   * name field in *service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | ClientDocument
  | HomeDocument
  | IndustryDocument
  | ProjectDocument
  | ServiceDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Heading 1
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * hero image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProjectEmbed → Default → Primary*
 */
export interface ProjectEmbedSliceDefaultPrimary {
  /**
   * embed link field in *ProjectEmbed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: project_embed.default.primary.embed_link
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed_link: prismic.EmbedField;
}

/**
 * Default variation for ProjectEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectEmbed*
 */
type ProjectEmbedSliceVariation = ProjectEmbedSliceDefault;

/**
 * ProjectEmbed Shared Slice
 *
 * - **API ID**: `project_embed`
 * - **Description**: ProjectEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectEmbedSlice = prismic.SharedSlice<
  "project_embed",
  ProjectEmbedSliceVariation
>;

/**
 * Primary content in *ProjectImages → Default → Primary*
 */
export interface ProjectImagesSliceDefaultPrimary {
  /**
   * project image field in *ProjectImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_images.default.primary.project_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImages*
 */
type ProjectImagesSliceVariation = ProjectImagesSliceDefault;

/**
 * ProjectImages Shared Slice
 *
 * - **API ID**: `project_images`
 * - **Description**: ProjectImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImagesSlice = prismic.SharedSlice<
  "project_images",
  ProjectImagesSliceVariation
>;

/**
 * Primary content in *ProjectTwoImages → Default → Primary*
 */
export interface ProjectTwoImagesSliceDefaultPrimary {
  /**
   * image 1 field in *ProjectTwoImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_two_images.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * image 2 field in *ProjectTwoImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_two_images.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectTwoImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTwoImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTwoImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectTwoImages*
 */
type ProjectTwoImagesSliceVariation = ProjectTwoImagesSliceDefault;

/**
 * ProjectTwoImages Shared Slice
 *
 * - **API ID**: `project_two_images`
 * - **Description**: ProjectTwoImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTwoImagesSlice = prismic.SharedSlice<
  "project_two_images",
  ProjectTwoImagesSliceVariation
>;

/**
 * Primary content in *ProjectVideoUrl → Default → Primary*
 */
export interface ProjectVideoUrlSliceDefaultPrimary {
  /**
   * Video url field in *ProjectVideoUrl → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video_url.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Default variation for ProjectVideoUrl Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoUrlSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectVideoUrlSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectVideoUrl*
 */
type ProjectVideoUrlSliceVariation = ProjectVideoUrlSliceDefault;

/**
 * ProjectVideoUrl Shared Slice
 *
 * - **API ID**: `project_video_url`
 * - **Description**: ProjectVideoUrl
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoUrlSlice = prismic.SharedSlice<
  "project_video_url",
  ProjectVideoUrlSliceVariation
>;

/**
 * Primary content in *ProjectVideoVimeo → Default → Primary*
 */
export interface ProjectVideoVimeoSliceDefaultPrimary {
  /**
   * Vimeo url field in *ProjectVideoVimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video_vimeo.default.primary.vimeo_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_url: prismic.KeyTextField;
}

/**
 * Default variation for ProjectVideoVimeo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoVimeoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectVideoVimeoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectVideoVimeo*
 */
type ProjectVideoVimeoSliceVariation = ProjectVideoVimeoSliceDefault;

/**
 * ProjectVideoVimeo Shared Slice
 *
 * - **API ID**: `project_video_vimeo`
 * - **Description**: ProjectVideoVimeo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoVimeoSlice = prismic.SharedSlice<
  "project_video_vimeo",
  ProjectVideoVimeoSliceVariation
>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * All projects field in *Projects → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.all_projects
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  all_projects: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ClientDocument,
      ClientDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      IndustryDocument,
      IndustryDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataProjectServicesItem,
      ProjectDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectEmbedSlice,
      ProjectEmbedSliceDefaultPrimary,
      ProjectEmbedSliceVariation,
      ProjectEmbedSliceDefault,
      ProjectImagesSlice,
      ProjectImagesSliceDefaultPrimary,
      ProjectImagesSliceVariation,
      ProjectImagesSliceDefault,
      ProjectTwoImagesSlice,
      ProjectTwoImagesSliceDefaultPrimary,
      ProjectTwoImagesSliceVariation,
      ProjectTwoImagesSliceDefault,
      ProjectVideoUrlSlice,
      ProjectVideoUrlSliceDefaultPrimary,
      ProjectVideoUrlSliceVariation,
      ProjectVideoUrlSliceDefault,
      ProjectVideoVimeoSlice,
      ProjectVideoVimeoSliceDefaultPrimary,
      ProjectVideoVimeoSliceVariation,
      ProjectVideoVimeoSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
    };
  }
}
