// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  project_embed: dynamic(() => import("./ProjectEmbed")),
  project_images: dynamic(() => import("./ProjectImages")),
  project_video: dynamic(() => import("./ProjectVideo")),
  project_video_url: dynamic(() => import("./ProjectVideoUrl")),
  project_video_vimeo: dynamic(() => import("./ProjectVideoVimeo")),
};
